import { DiscoverNotification, DiscoveryFeedItem } from '@/types';

// Demo data for testing the app without Convex backend

// Demo discover notifications (cycle every 30s)
export const DEMO_DISCOVER_NOTIFICATIONS: DiscoverNotification[] = [
  {
    id: 'demo_notif_1',
    type: 'crossed_paths',
    message: 'You crossed paths with 3 people nearby today',
    navigateTo: '/(main)/crossed-paths',
    createdAt: Date.now(),
  },
  {
    id: 'demo_notif_2',
    type: 'new_matches',
    message: 'Someone new liked your profile — check it out',
    navigateTo: '/(main)/likes',
    createdAt: Date.now(),
  },
  {
    id: 'demo_notif_3',
    type: 'interest_match',
    message: '5 coffee lovers are active near you right now',
    navigateTo: '/(main)/(tabs)/explore',
    createdAt: Date.now(),
  },
];

// Demo discovery feed items
export const DEMO_FEED_ITEMS: DiscoveryFeedItem[] = [
  { id: 'feed_1', type: 'crossed_paths', icon: '👣', message: '3 crossed paths in the last 24h', navigateTo: '/(main)/crossed-paths' },
  { id: 'feed_2', type: 'activity_highlight', icon: '🔥', message: '8 coffee lovers are active near you', navigateTo: '/(main)/(tabs)/explore' },
  { id: 'feed_3', type: 'unread_messages', icon: '💬', message: '2 unread messages waiting for you', navigateTo: '/(main)/(tabs)/messages' },
];

export const DEMO_USER = {
  _id: 'demo_user_1',
  name: 'You',
  email: 'demo@mira.app',
  gender: 'male',
  dateOfBirth: '1995-01-15',
  bio: 'This is demo mode! Set up Convex to use real data.',
  isVerified: true,
  city: 'Mumbai',
  latitude: 19.076,
  longitude: 72.8777,
  isDiscoveryPaused: false,
  discoveryPausedUntil: undefined,
  subscriptionTier: 'premium',
  lookingFor: ['female'],
  relationshipIntent: ['long_term'],
  activities: ['coffee', 'movies'],
  minAge: 18,
  maxAge: 35,
  maxDistance: 50,
  likesRemaining: 50,
  superLikesRemaining: 5,
  messagesRemaining: 10,
  photos: [
    { url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400' }
  ],
};

export const DEMO_PROFILES = [
  {
    _id: 'demo_profile_1',
    name: 'Priya',
    age: 25,
    gender: 'female',
    bio: 'Love traveling and trying new cuisines! Looking for someone to explore the city with.',
    isVerified: true,
    city: 'Mumbai',
    distance: 5,
    latitude: 19.082,
    longitude: 72.871,
    lastSeenArea: 'Bandra West',
    relationshipIntent: ['long_term'],
    activities: ['coffee', 'travel', 'foodie'],
    profilePrompts: [
      { question: 'My ideal first date is...', answer: 'A sunset walk along Marine Drive followed by street food at Juhu Beach' },
      { question: 'A green flag for me is...', answer: 'Someone who asks follow-up questions and actually listens' },
      { question: "I'm happiest when...", answer: 'Planning my next trip or cooking something new in the kitchen' },
    ],
    photos: [
      { url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400' },
      { url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400' },
      { url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400' },
      { url: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400' },
    ],
  },
  {
    _id: 'demo_profile_2',
    name: 'Ananya',
    age: 23,
    gender: 'female',
    bio: 'Software engineer by day, dancer by night. Let\'s grab coffee!',
    isVerified: true,
    city: 'Bangalore',
    distance: 12,
    latitude: 12.9716,
    longitude: 77.5946,
    lastSeenArea: 'Koramangala',
    relationshipIntent: ['figuring_out'],
    activities: ['coffee', 'concerts', 'gym_partner'],
    profilePrompts: [
      { question: 'I geek out about...', answer: 'Distributed systems, Kathak dance, and finding the best filter coffee in every city' },
      { question: 'My most spontaneous moment was...', answer: 'Signing up for a 5K run 30 minutes before it started — finished it too!' },
    ],
    photos: [
      { url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400' },
      { url: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400' },
      { url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400' },
      { url: 'https://images.unsplash.com/photo-1506956191951-7a88da4435e5?w=400' },
      { url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400' },
    ],
  },
  {
    _id: 'demo_profile_3',
    name: 'Meera',
    age: 27,
    gender: 'female',
    bio: 'Book lover, coffee addict, and amateur photographer. Looking for meaningful connections.',
    isVerified: false,
    city: 'Mumbai',
    distance: 1.8,
    latitude: 19.0596,
    longitude: 72.8295,
    lastSeenArea: 'Dadar',
    relationshipIntent: ['long_term', 'short_to_long'],
    activities: ['coffee', 'art_culture', 'photography'],
    profilePrompts: [
      { question: 'The way to my heart is...', answer: 'A handwritten note, a good book recommendation, or just comfortable silence together' },
      { question: 'I feel most connected when...', answer: 'Having deep conversations over chai while it rains outside' },
    ],
    photos: [
      { url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400' },
      { url: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400' },
      { url: 'https://images.unsplash.com/photo-1464863979621-258859e62245?w=400' },
      { url: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=400' },
    ],
  },
  {
    _id: 'demo_profile_4',
    name: 'Aisha',
    age: 24,
    gender: 'female',
    bio: 'Fitness enthusiast and food blogger. Swipe right if you love dogs!',
    isVerified: true,
    city: 'Mumbai',
    distance: 0.8,
    latitude: 19.0728,
    longitude: 72.8826,
    lastSeenArea: 'Kurla West',
    relationshipIntent: ['new_friends', 'open_to_anything'],
    activities: ['gym_partner', 'foodie', 'outdoors'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400' },
      { url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400' },
      { url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400' },
    ],
  },
  {
    _id: 'demo_profile_5',
    name: 'Kavya',
    age: 26,
    gender: 'female',
    bio: 'Marketing professional who loves weekend getaways. Looking for my travel partner!',
    isVerified: true,
    city: 'Pune',
    distance: 15,
    latitude: 18.5204,
    longitude: 73.8567,
    lastSeenArea: 'Koregaon Park',
    relationshipIntent: ['long_term'],
    activities: ['travel', 'road_trip', 'beach_pool'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400' },
      { url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400' },
      { url: 'https://images.unsplash.com/photo-1485893086445-ed75865251e0?w=400' },
      { url: 'https://images.unsplash.com/photo-1504439904031-93ded9f93e4e?w=400' },
      { url: 'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=400' },
    ],
  },
  {
    _id: 'demo_profile_6',
    name: 'Riya',
    age: 22,
    gender: 'female',
    bio: 'Film school grad who talks in movie quotes. Looking for my co-star in life.',
    isVerified: true,
    city: 'Mumbai',
    distance: 1.2,
    latitude: 19.0895,
    longitude: 72.8656,
    lastSeenArea: 'Andheri East',
    relationshipIntent: ['long_term'],
    activities: ['movies', 'art_culture', 'nightlife'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400' },
      { url: 'https://images.unsplash.com/photo-1521146764736-56c929d59c83?w=400' },
      { url: 'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=400' },
      { url: 'https://images.unsplash.com/photo-1499557354967-2b2d8910bcca?w=400' },
    ],
  },
  {
    _id: 'demo_profile_7',
    name: 'Sneha',
    age: 28,
    gender: 'female',
    bio: 'Doctor who prescribes laughter as the best medicine. Weekend hiker and chai lover.',
    isVerified: true,
    city: 'Hyderabad',
    distance: 20,
    latitude: 17.385,
    longitude: 78.4867,
    lastSeenArea: 'Jubilee Hills',
    relationshipIntent: ['long_term', 'short_to_long'],
    activities: ['outdoors', 'coffee', 'travel'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400' },
      { url: 'https://images.unsplash.com/photo-1513379733131-47fc74b45fc7?w=400' },
      { url: 'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=400' },
    ],
  },
  {
    _id: 'demo_profile_8',
    name: 'Diya',
    age: 24,
    gender: 'female',
    bio: 'Graphic designer with a love for street food and spontaneous road trips.',
    isVerified: false,
    city: 'Jaipur',
    distance: 30,
    latitude: 26.9124,
    longitude: 75.7873,
    lastSeenArea: 'C-Scheme',
    relationshipIntent: ['figuring_out'],
    activities: ['road_trip', 'foodie', 'photography'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1504439904031-93ded9f93e4e?w=400' },
      { url: 'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=400' },
      { url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400' },
      { url: 'https://images.unsplash.com/photo-1488716820095-cbe80883c496?w=400' },
    ],
  },
  {
    _id: 'demo_profile_9',
    name: 'Nisha',
    age: 26,
    gender: 'female',
    bio: 'Yoga instructor and vegan foodie. Looking for positive vibes and deep conversations.',
    isVerified: true,
    city: 'Mumbai',
    distance: 2.5,
    latitude: 19.0544,
    longitude: 72.8405,
    lastSeenArea: 'Mahim',
    relationshipIntent: ['open_to_anything'],
    activities: ['gym_partner', 'beach_pool', 'foodie'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1506956191951-7a88da4435e5?w=400' },
      { url: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400' },
      { url: 'https://images.unsplash.com/photo-1502767089025-6572583495f9?w=400' },
      { url: 'https://images.unsplash.com/photo-1484399172022-72a90b12e3c1?w=400' },
    ],
  },
  {
    _id: 'demo_profile_10',
    name: 'Tara',
    age: 25,
    gender: 'female',
    bio: 'Architect who builds dreams during the day and stargazes at night. Cat mom.',
    isVerified: true,
    city: 'Chennai',
    distance: 18,
    latitude: 13.0827,
    longitude: 80.2707,
    lastSeenArea: 'T. Nagar',
    relationshipIntent: ['long_term'],
    activities: ['art_culture', 'coffee', 'photography'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=400' },
      { url: 'https://images.unsplash.com/photo-1502767089025-6572583495f9?w=400' },
      { url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400' },
    ],
  },
  {
    _id: 'demo_profile_11',
    name: 'Zara',
    age: 23,
    gender: 'female',
    bio: 'Fashion blogger who loves trying new restaurants. Fluent in sarcasm and three languages.',
    isVerified: true,
    city: 'Mumbai',
    distance: 2.1,
    latitude: 19.0640,
    longitude: 72.8685,
    lastSeenArea: 'Sion',
    relationshipIntent: ['short_term', 'new_friends'],
    activities: ['nightlife', 'foodie', 'brunch'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1464863979621-258859e62245?w=400' },
      { url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400' },
      { url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400' },
      { url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400' },
    ],
  },
  {
    _id: 'demo_profile_12',
    name: 'Isha',
    age: 27,
    gender: 'female',
    bio: 'Music producer and vinyl collector. Will judge you by your playlist. Dog person.',
    isVerified: false,
    city: 'Mumbai',
    distance: 1.5,
    latitude: 19.0990,
    longitude: 72.8475,
    lastSeenArea: 'Juhu',
    relationshipIntent: ['figuring_out'],
    activities: ['concerts', 'nightlife', 'coffee'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1485893086445-ed75865251e0?w=400' },
      { url: 'https://images.unsplash.com/photo-1484399172022-72a90b12e3c1?w=400' },
      { url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400' },
      { url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400' },
      { url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400' },
    ],
  },
  {
    _id: 'demo_profile_13',
    name: 'Pooja',
    age: 29,
    gender: 'female',
    bio: 'Startup founder who runs on coffee and ambition. Looking for someone equally driven.',
    isVerified: true,
    city: 'Bangalore',
    distance: 14,
    latitude: 12.9352,
    longitude: 77.6245,
    lastSeenArea: 'Indiranagar',
    relationshipIntent: ['long_term'],
    activities: ['coffee', 'gym_partner', 'brunch'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400' },
      { url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400' },
      { url: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=400' },
    ],
  },
  {
    _id: 'demo_profile_14',
    name: 'Simran',
    age: 24,
    gender: 'female',
    bio: 'Still waiting for my DDLJ moment at the train station. Bollywood fan and hopeless romantic.',
    isVerified: true,
    city: 'Chandigarh',
    distance: 35,
    latitude: 30.7333,
    longitude: 76.7794,
    lastSeenArea: 'Sector 17',
    relationshipIntent: ['long_term'],
    activities: ['movies', 'travel', 'date_night'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=400' },
      { url: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400' },
      { url: 'https://images.unsplash.com/photo-1464863979621-258859e62245?w=400' },
      { url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400' },
    ],
  },
  {
    _id: 'demo_profile_15',
    name: 'Aditi',
    age: 22,
    gender: 'female',
    bio: 'College student who loves gaming marathons and midnight snacks. Looking for my player 2.',
    isVerified: false,
    city: 'Pune',
    distance: 16,
    latitude: 18.5362,
    longitude: 73.8983,
    lastSeenArea: 'Viman Nagar',
    relationshipIntent: ['new_friends', 'figuring_out'],
    activities: ['gaming', 'movies', 'foodie'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1488716820095-cbe80883c496?w=400' },
      { url: 'https://images.unsplash.com/photo-1506956191951-7a88da4435e5?w=400' },
      { url: 'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=400' },
    ],
  },
  {
    _id: 'demo_profile_16',
    name: 'Lakshmi',
    age: 26,
    gender: 'female',
    bio: 'Classical dancer turned contemporary artist. Life is too short for boring conversations.',
    isVerified: true,
    city: 'Kochi',
    distance: 40,
    latitude: 9.9312,
    longitude: 76.2673,
    lastSeenArea: 'Fort Kochi',
    relationshipIntent: ['open_to_anything'],
    activities: ['art_culture', 'concerts', 'beach_pool'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1513379733131-47fc74b45fc7?w=400' },
      { url: 'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=400' },
      { url: 'https://images.unsplash.com/photo-1504439904031-93ded9f93e4e?w=400' },
      { url: 'https://images.unsplash.com/photo-1521146764736-56c929d59c83?w=400' },
    ],
  },
  {
    _id: 'demo_profile_17',
    name: 'Fatima',
    age: 25,
    gender: 'female',
    bio: 'Journalist by profession, traveler by passion. Always chasing the next story.',
    isVerified: true,
    city: 'Mumbai',
    distance: 2.8,
    latitude: 19.0436,
    longitude: 72.8204,
    lastSeenArea: 'Worli',
    relationshipIntent: ['short_to_long'],
    activities: ['travel', 'photography', 'coffee'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1499557354967-2b2d8910bcca?w=400' },
      { url: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400' },
      { url: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400' },
      { url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400' },
    ],
  },
  {
    _id: 'demo_profile_18',
    name: 'Kriti',
    age: 28,
    gender: 'female',
    bio: 'Chef who believes the way to the heart is through the stomach. Weekend baker.',
    isVerified: true,
    city: 'Mumbai',
    distance: 1.0,
    latitude: 19.0760,
    longitude: 72.8910,
    lastSeenArea: 'Chembur',
    relationshipIntent: ['long_term'],
    activities: ['foodie', 'brunch', 'date_night'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400' },
      { url: 'https://images.unsplash.com/photo-1475823678248-624fc6f85785?w=400' },
      { url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400' },
    ],
  },
  {
    _id: 'demo_profile_19',
    name: 'Neha',
    age: 23,
    gender: 'female',
    bio: 'PhD student researching astrophysics. Can explain black holes but not my love life.',
    isVerified: false,
    city: 'Bangalore',
    distance: 11,
    latitude: 12.9780,
    longitude: 77.5720,
    lastSeenArea: 'Malleshwaram',
    relationshipIntent: ['figuring_out'],
    activities: ['study_date', 'coffee', 'outdoors'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1557862921-37829c790f19?w=400' },
      { url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400' },
      { url: 'https://images.unsplash.com/photo-1513379733131-47fc74b45fc7?w=400' },
      { url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400' },
    ],
  },
  {
    _id: 'demo_profile_20',
    name: 'Sana',
    age: 27,
    gender: 'female',
    bio: 'Interior designer who rearranges furniture for fun. Love a good flea market find.',
    isVerified: true,
    city: 'Mumbai',
    distance: 2.3,
    latitude: 19.0558,
    longitude: 72.8346,
    lastSeenArea: 'Prabhadevi',
    relationshipIntent: ['long_term', 'short_to_long'],
    activities: ['art_culture', 'coffee', 'this_weekend'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400' },
      { url: 'https://images.unsplash.com/photo-1505033575518-a36ea2ef75ae?w=400' },
      { url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400' },
    ],
  },
  {
    _id: 'demo_profile_21',
    name: 'Tanvi',
    age: 24,
    gender: 'female',
    bio: 'Adventure junkie - skydiving, scuba, bungee jumping. Life begins at the edge of your comfort zone.',
    isVerified: true,
    city: 'Mumbai',
    distance: 2.9,
    latitude: 19.1075,
    longitude: 72.8263,
    lastSeenArea: 'Versova',
    relationshipIntent: ['open_to_anything'],
    activities: ['outdoors', 'travel', 'sports'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1529635204996-ef54f42e1804?w=400' },
    ],
  },
  {
    _id: 'demo_profile_22',
    name: 'Divya',
    age: 26,
    gender: 'female',
    bio: 'Lawyer who argues for a living but promises not to at home. Wine and book club regular.',
    isVerified: true,
    city: 'Mumbai',
    distance: 0.5,
    latitude: 19.0745,
    longitude: 72.8800,
    lastSeenArea: 'Kurla',
    relationshipIntent: ['long_term'],
    activities: ['brunch', 'date_night', 'art_culture'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1546961342-ea1f71b193f3?w=400' },
      { url: 'https://images.unsplash.com/photo-1504703395950-b89145a5425b?w=400' },
    ],
  },
  {
    _id: 'demo_profile_23',
    name: 'Shreya',
    age: 25,
    gender: 'female',
    bio: 'Stand-up comedian and meme connoisseur. If you can make me laugh, you have my attention.',
    isVerified: false,
    city: 'Pune',
    distance: 17,
    latitude: 18.5074,
    longitude: 73.8077,
    lastSeenArea: 'Deccan Gymkhana',
    relationshipIntent: ['new_friends', 'figuring_out'],
    activities: ['nightlife', 'movies', 'coffee'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=400' },
    ],
  },
  {
    _id: 'demo_profile_24',
    name: 'Pallavi',
    age: 29,
    gender: 'female',
    bio: 'Wildlife photographer who has spent more time with elephants than humans. Looking to change that.',
    isVerified: true,
    city: 'Mysore',
    distance: 28,
    latitude: 12.2958,
    longitude: 76.6394,
    lastSeenArea: 'Gokulam',
    relationshipIntent: ['long_term'],
    activities: ['photography', 'outdoors', 'travel'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1491349174775-aaafddd81942?w=400' },
      { url: 'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?w=400' },
    ],
  },
  {
    _id: 'demo_profile_25',
    name: 'Jhanvi',
    age: 22,
    gender: 'female',
    bio: 'Dance teacher and fitness freak. Morning person who actually enjoys 5 AM runs.',
    isVerified: true,
    city: 'Mumbai',
    distance: 1.7,
    latitude: 19.0650,
    longitude: 72.8510,
    lastSeenArea: 'Matunga',
    relationshipIntent: ['short_term', 'open_to_anything'],
    activities: ['gym_partner', 'sports', 'free_tonight'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?w=400' },
    ],
  },
  {
    _id: 'demo_profile_26',
    name: 'Radhika',
    age: 25,
    gender: 'female',
    bio: 'Veterinarian who talks to animals more than humans. Weekend potter and tea enthusiast.',
    isVerified: true,
    city: 'Mumbai',
    distance: 3.4,
    latitude: 19.0810,
    longitude: 72.8900,
    lastSeenArea: 'Powai',
    relationshipIntent: ['long_term'],
    activities: ['coffee', 'art_culture', 'outdoors'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400' },
    ],
  },
  {
    _id: 'demo_profile_27',
    name: 'Manya',
    age: 23,
    gender: 'female',
    bio: 'Content creator and beach bum. If you can surf, you already have my attention.',
    isVerified: false,
    city: 'Goa',
    distance: 42,
    latitude: 15.2993,
    longitude: 74.1240,
    lastSeenArea: 'Anjuna',
    relationshipIntent: ['fwb', 'short_term'],
    activities: ['beach_pool', 'photography', 'nightlife'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1529635204996-ef54f42e1804?w=400' },
      { url: 'https://images.unsplash.com/photo-1502767089025-6572583495f9?w=400' },
    ],
  },
  {
    _id: 'demo_profile_28',
    name: 'Keerthi',
    age: 27,
    gender: 'female',
    bio: 'Data scientist by day, karaoke queen by night. Looking for someone to harmonize with.',
    isVerified: true,
    city: 'Hyderabad',
    distance: 22,
    latitude: 17.4400,
    longitude: 78.3489,
    lastSeenArea: 'Gachibowli',
    relationshipIntent: ['short_to_long'],
    activities: ['concerts', 'nightlife', 'brunch'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1513379733131-47fc74b45fc7?w=400' },
    ],
  },
  {
    _id: 'demo_profile_29',
    name: 'Anushka',
    age: 24,
    gender: 'female',
    bio: 'Architect who builds dreams. Volunteer at animal shelters on weekends. Dog mom of two.',
    isVerified: true,
    city: 'Mumbai',
    distance: 1.3,
    latitude: 19.0620,
    longitude: 72.8350,
    lastSeenArea: 'Lower Parel',
    relationshipIntent: ['long_term', 'figuring_out'],
    activities: ['volunteering', 'coffee', 'outdoors'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1499557354967-2b2d8910bcca?w=400' },
      { url: 'https://images.unsplash.com/photo-1505033575518-a36ea2ef75ae?w=400' },
    ],
  },
  {
    _id: 'demo_profile_30',
    name: 'Trisha',
    age: 26,
    gender: 'female',
    bio: 'HR professional who reads people for a living. Gym rat and smoothie addict.',
    isVerified: true,
    city: 'Bangalore',
    distance: 13,
    latitude: 12.9600,
    longitude: 77.6410,
    lastSeenArea: 'HSR Layout',
    relationshipIntent: ['long_to_short'],
    activities: ['gym_partner', 'brunch', 'this_weekend'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=400' },
    ],
  },
  {
    _id: 'demo_profile_31',
    name: 'Vanya',
    age: 22,
    gender: 'female',
    bio: 'Theatre actress and poetry slam champion. Life is too short for small talk.',
    isVerified: false,
    city: 'Mumbai',
    distance: 2.0,
    latitude: 19.0700,
    longitude: 72.8600,
    lastSeenArea: 'Bandra East',
    relationshipIntent: ['figuring_out', 'new_friends'],
    activities: ['art_culture', 'concerts', 'coffee'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1546961342-ea1f71b193f3?w=400' },
    ],
  },
  {
    _id: 'demo_profile_32',
    name: 'Myra',
    age: 28,
    gender: 'female',
    bio: 'Investment banker escaping spreadsheets. Loves wine, cheese, and existential conversations.',
    isVerified: true,
    city: 'Mumbai',
    distance: 0.9,
    latitude: 19.0770,
    longitude: 72.8850,
    lastSeenArea: 'BKC',
    relationshipIntent: ['long_term'],
    activities: ['date_night', 'brunch', 'travel'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1504703395950-b89145a5425b?w=400' },
      { url: 'https://images.unsplash.com/photo-1475823678248-624fc6f85785?w=400' },
    ],
  },
  {
    _id: 'demo_profile_33',
    name: 'Charvi',
    age: 24,
    gender: 'female',
    bio: 'Game developer and D&D dungeon master. Looking for my player two.',
    isVerified: true,
    city: 'Pune',
    distance: 15,
    latitude: 18.5600,
    longitude: 73.9166,
    lastSeenArea: 'Hinjewadi',
    relationshipIntent: ['open_to_anything'],
    activities: ['gaming', 'movies', 'foodie'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1488716820095-cbe80883c496?w=400' },
    ],
  },
  {
    _id: 'demo_profile_34',
    name: 'Navya',
    age: 25,
    gender: 'female',
    bio: 'Physiotherapist and marathon runner. Let me fix your posture and steal your heart.',
    isVerified: true,
    city: 'Mumbai',
    distance: 2.6,
    latitude: 19.1000,
    longitude: 72.8370,
    lastSeenArea: 'Goregaon',
    relationshipIntent: ['short_to_long'],
    activities: ['sports', 'gym_partner', 'road_trip'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=400' },
      { url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400' },
    ],
  },
  {
    _id: 'demo_profile_35',
    name: 'Kiara',
    age: 23,
    gender: 'female',
    bio: 'Journalism student chasing stories and sunsets. Will write about you in my diary.',
    isVerified: false,
    city: 'Delhi',
    distance: 25,
    latitude: 28.6139,
    longitude: 77.2090,
    lastSeenArea: 'Connaught Place',
    relationshipIntent: ['fwb', 'figuring_out'],
    activities: ['photography', 'travel', 'nightlife'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400' },
    ],
  },
  {
    _id: 'demo_profile_36',
    name: 'Saanvi',
    age: 26,
    gender: 'female',
    bio: 'Music therapist and vinyl collector. Healing one song at a time.',
    isVerified: true,
    city: 'Mumbai',
    distance: 1.8,
    latitude: 19.0550,
    longitude: 72.8400,
    lastSeenArea: 'Parel',
    relationshipIntent: ['long_term', 'short_to_long'],
    activities: ['concerts', 'coffee', 'art_culture'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1485893086445-ed75865251e0?w=400' },
      { url: 'https://images.unsplash.com/photo-1484399172022-72a90b12e3c1?w=400' },
    ],
  },
  {
    _id: 'demo_profile_37',
    name: 'Inaya',
    age: 27,
    gender: 'female',
    bio: 'Pastry chef with a sweet tooth and sweeter personality. Will bake for first dates.',
    isVerified: true,
    city: 'Mumbai',
    distance: 3.1,
    latitude: 19.1100,
    longitude: 72.8700,
    lastSeenArea: 'Malad',
    relationshipIntent: ['long_term'],
    activities: ['foodie', 'date_night', 'this_weekend'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400' },
    ],
  },
  {
    _id: 'demo_profile_38',
    name: 'Aaliya',
    age: 24,
    gender: 'female',
    bio: 'Scuba diver and marine biology student. More comfortable underwater than on land.',
    isVerified: false,
    city: 'Mumbai',
    distance: 4.5,
    latitude: 19.0420,
    longitude: 72.8200,
    lastSeenArea: 'Haji Ali',
    relationshipIntent: ['open_to_anything', 'new_friends'],
    activities: ['beach_pool', 'outdoors', 'travel'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?w=400' },
    ],
  },
  {
    _id: 'demo_profile_39',
    name: 'Ritika',
    age: 25,
    gender: 'female',
    bio: 'UX designer obsessed with making things beautiful. Brunch is my love language.',
    isVerified: true,
    city: 'Mumbai',
    distance: 1.1,
    latitude: 19.0680,
    longitude: 72.8540,
    lastSeenArea: 'Dadar West',
    relationshipIntent: ['short_term', 'short_to_long'],
    activities: ['brunch', 'art_culture', 'coffee'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400' },
      { url: 'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=400' },
    ],
  },
  {
    _id: 'demo_profile_40',
    name: 'Gauri',
    age: 29,
    gender: 'female',
    bio: 'Pilates instructor and organic farmer on weekends. Looking for grounded souls.',
    isVerified: true,
    city: 'Mumbai',
    distance: 5.2,
    latitude: 19.1200,
    longitude: 72.8450,
    lastSeenArea: 'Kandivali',
    relationshipIntent: ['long_term'],
    activities: ['gym_partner', 'outdoors', 'volunteering'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1491349174775-aaafddd81942?w=400' },
    ],
  },
  {
    _id: 'demo_profile_41',
    name: 'Tanya',
    age: 23,
    gender: 'female',
    bio: 'Startup founder who codes at night and hikes at dawn. Need someone to keep up.',
    isVerified: true,
    city: 'Mumbai',
    distance: 2.2,
    latitude: 19.0740,
    longitude: 72.8580,
    lastSeenArea: 'Bandra West',
    relationshipIntent: ['fwb', 'short_term'],
    activities: ['free_tonight', 'nightlife', 'coffee'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400' },
    ],
  },
  {
    _id: 'demo_profile_42',
    name: 'Nisha',
    age: 25,
    gender: 'female',
    bio: 'Graphic designer and cocktail mixology student. Let me make you a drink.',
    isVerified: false,
    city: 'Mumbai',
    distance: 1.6,
    latitude: 19.0600,
    longitude: 72.8370,
    lastSeenArea: 'Worli',
    relationshipIntent: ['fwb', 'figuring_out'],
    activities: ['free_tonight', 'nightlife', 'art_culture'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400' },
      { url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400' },
    ],
  },
  {
    _id: 'demo_profile_43',
    name: 'Aditi',
    age: 24,
    gender: 'female',
    bio: 'Standup comedian testing new material. Laugh at my jokes and I am yours.',
    isVerified: true,
    city: 'Mumbai',
    distance: 3.8,
    latitude: 19.0920,
    longitude: 72.8410,
    lastSeenArea: 'Andheri',
    relationshipIntent: ['short_term', 'open_to_anything'],
    activities: ['free_tonight', 'this_weekend', 'nightlife'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400' },
    ],
  },
  {
    _id: 'demo_profile_44',
    name: 'Zara',
    age: 26,
    gender: 'female',
    bio: 'Weekend DJ, weekday analyst. Looking for someone who enjoys both spreadsheets and beats.',
    isVerified: true,
    city: 'Mumbai',
    distance: 0.8,
    latitude: 19.0760,
    longitude: 72.8820,
    lastSeenArea: 'BKC',
    relationshipIntent: ['figuring_out'],
    activities: ['this_weekend', 'concerts', 'nightlife'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400' },
      { url: 'https://images.unsplash.com/photo-1502767089025-6572583495f9?w=400' },
    ],
  },
  {
    _id: 'demo_profile_45',
    name: 'Isha',
    age: 27,
    gender: 'female',
    bio: 'Yoga instructor finding balance. Flexible in more ways than one.',
    isVerified: true,
    city: 'Mumbai',
    distance: 4.0,
    latitude: 19.0500,
    longitude: 72.8300,
    lastSeenArea: 'Prabhadevi',
    relationshipIntent: ['long_term', 'short_to_long'],
    activities: ['gym_partner', 'this_weekend', 'outdoors'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400' },
    ],
  },
  {
    _id: 'demo_profile_46',
    name: 'Kavya',
    age: 22,
    gender: 'female',
    bio: 'Final year med student who needs a study break. Know any good cafes?',
    isVerified: false,
    city: 'Mumbai',
    distance: 1.4,
    latitude: 19.0680,
    longitude: 72.8490,
    lastSeenArea: 'Dadar',
    relationshipIntent: ['new_friends', 'figuring_out'],
    activities: ['coffee', 'study_date', 'free_tonight'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400' },
    ],
  },
  {
    _id: 'demo_profile_47',
    name: 'Rhea',
    age: 28,
    gender: 'female',
    bio: 'Event planner who throws the best parties. Always know where the fun is.',
    isVerified: true,
    city: 'Mumbai',
    distance: 2.9,
    latitude: 19.0850,
    longitude: 72.8360,
    lastSeenArea: 'Juhu',
    relationshipIntent: ['short_term', 'fwb'],
    activities: ['free_tonight', 'this_weekend', 'nightlife', 'brunch'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=400' },
      { url: 'https://images.unsplash.com/photo-1485893086445-ed75865251e0?w=400' },
    ],
  },
  {
    _id: 'demo_profile_48',
    name: 'Prachi',
    age: 25,
    gender: 'female',
    bio: 'Wildlife photographer and documentary filmmaker. Have camera, will travel.',
    isVerified: true,
    city: 'Mumbai',
    distance: 3.5,
    latitude: 19.1050,
    longitude: 72.8700,
    lastSeenArea: 'Goregaon East',
    relationshipIntent: ['long_term'],
    activities: ['photography', 'travel', 'outdoors'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=400' },
    ],
  },
  {
    _id: 'demo_profile_49',
    name: 'Sneha',
    age: 24,
    gender: 'female',
    bio: 'Board game cafe owner. Challenge me to Catan and see what happens.',
    isVerified: true,
    city: 'Mumbai',
    distance: 1.9,
    latitude: 19.0590,
    longitude: 72.8450,
    lastSeenArea: 'Parel',
    relationshipIntent: ['new_friends', 'short_to_long'],
    activities: ['gaming', 'coffee', 'this_weekend'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1504703395950-b89145a5425b?w=400' },
    ],
  },
  {
    _id: 'demo_profile_50',
    name: 'Diya',
    age: 26,
    gender: 'female',
    bio: 'Marine biologist who moonlights as a salsa dancer. Ocean by day, dance floor by night.',
    isVerified: false,
    city: 'Mumbai',
    distance: 4.3,
    latitude: 19.0430,
    longitude: 72.8210,
    lastSeenArea: 'Marine Drive',
    relationshipIntent: ['open_to_anything'],
    activities: ['beach_pool', 'free_tonight', 'concerts'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?w=400' },
      { url: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400' },
    ],
  },
  // --- Nearby profiles spread in all 360° directions around demo user (19.076, 72.8777) ---
  {
    _id: 'demo_nearby_n',
    name: 'Anita',
    age: 24,
    gender: 'female',
    bio: 'Morning runner who loves sunrise views from Powai lake. Tea > coffee.',
    isVerified: true,
    city: 'Mumbai',
    distance: 1.5,
    latitude: 19.0895,   // ~1.5km North
    longitude: 72.8777,
    lastSeenArea: 'Powai',
    relationshipIntent: ['long_term'],
    activities: ['gym_partner', 'outdoors', 'coffee'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400' },
    ],
  },
  {
    _id: 'demo_nearby_ne',
    name: 'Minal',
    age: 23,
    gender: 'female',
    bio: 'Data analyst who finds patterns in everything — even dating. Dog mom to a golden retriever.',
    isVerified: true,
    city: 'Mumbai',
    distance: 2.0,
    latitude: 19.0870,   // ~2km NE
    longitude: 72.8920,
    lastSeenArea: 'Ghatkopar West',
    relationshipIntent: ['figuring_out'],
    activities: ['coffee', 'movies', 'gaming'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400' },
    ],
  },
  {
    _id: 'demo_nearby_e',
    name: 'Swati',
    age: 26,
    gender: 'female',
    bio: 'Teacher by day, karaoke queen by night. Looking for someone who can handle my singing.',
    isVerified: false,
    city: 'Mumbai',
    distance: 1.8,
    latitude: 19.0760,   // ~1.8km East
    longitude: 72.8950,
    lastSeenArea: 'Vikhroli',
    relationshipIntent: ['new_friends', 'open_to_anything'],
    activities: ['concerts', 'nightlife', 'foodie'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400' },
    ],
  },
  {
    _id: 'demo_nearby_se',
    name: 'Gauri',
    age: 27,
    gender: 'female',
    bio: 'Chartered accountant who can calculate the tip faster than you can say dessert.',
    isVerified: true,
    city: 'Mumbai',
    distance: 2.2,
    latitude: 19.0640,   // ~2.2km SE
    longitude: 72.8930,
    lastSeenArea: 'Chembur East',
    relationshipIntent: ['long_term'],
    activities: ['brunch', 'date_night', 'travel'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400' },
    ],
  },
  {
    _id: 'demo_nearby_s',
    name: 'Hema',
    age: 25,
    gender: 'female',
    bio: 'Freelance writer crafting stories between coffee refills. Introvert with extrovert energy.',
    isVerified: true,
    city: 'Mumbai',
    distance: 1.2,
    latitude: 19.0650,   // ~1.2km South
    longitude: 72.8777,
    lastSeenArea: 'Sion West',
    relationshipIntent: ['short_to_long'],
    activities: ['coffee', 'art_culture', 'study_date'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400' },
    ],
  },
  {
    _id: 'demo_nearby_sw',
    name: 'Vani',
    age: 22,
    gender: 'female',
    bio: 'Animation student who draws her feelings. Weekend flea market explorer.',
    isVerified: false,
    city: 'Mumbai',
    distance: 2.5,
    latitude: 19.0630,   // ~2.5km SW
    longitude: 72.8620,
    lastSeenArea: 'Dharavi',
    relationshipIntent: ['new_friends'],
    activities: ['art_culture', 'photography', 'this_weekend'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400' },
    ],
  },
  {
    _id: 'demo_nearby_w',
    name: 'Jaya',
    age: 28,
    gender: 'female',
    bio: 'Physiotherapist who fixes people for a living. Bollywood dance enthusiast on weekends.',
    isVerified: true,
    city: 'Mumbai',
    distance: 1.6,
    latitude: 19.0760,   // ~1.6km West
    longitude: 72.8620,
    lastSeenArea: 'Matunga East',
    relationshipIntent: ['long_term', 'short_to_long'],
    activities: ['gym_partner', 'movies', 'foodie'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1506956191951-7a88da4435e5?w=400' },
    ],
  },
  {
    _id: 'demo_nearby_nw',
    name: 'Rhea',
    age: 24,
    gender: 'female',
    bio: 'UX designer obsessed with clean interfaces and messy bookshelves. Cat person.',
    isVerified: true,
    city: 'Mumbai',
    distance: 2.0,
    latitude: 19.0880,   // ~2km NW
    longitude: 72.8650,
    lastSeenArea: 'Andheri East',
    relationshipIntent: ['open_to_anything'],
    activities: ['coffee', 'gaming', 'photography'],
    photos: [
      { url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400' },
    ],
  },
];

export const DEMO_MATCHES = [
  {
    id: 'match_1',
    otherUser: {
      id: 'demo_profile_1',
      name: 'Priya',
      photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
      lastActive: Date.now() - 1000 * 60 * 5,
      isVerified: true,
    },
    lastMessage: {
      content: 'Hey! How are you?',
      type: 'text',
      senderId: 'demo_profile_1',
      createdAt: Date.now() - 1000 * 60 * 30,
    },
    unreadCount: 1,
    isPreMatch: false,
  },
  {
    id: 'match_2',
    otherUser: {
      id: 'demo_profile_3',
      name: 'Meera',
      photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
      lastActive: Date.now() - 1000 * 60 * 60,
      isVerified: false,
    },
    lastMessage: null,
    unreadCount: 0,
    isPreMatch: false,
  },
];

export const DEMO_LIKES = [
  {
    likeId: 'like_1',
    userId: 'demo_profile_4',
    action: 'like',
    message: null,
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
    name: 'Aisha',
    age: 24,
    photoUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400',
    isBlurred: false,
  },
  {
    likeId: 'like_2',
    userId: 'demo_profile_5',
    action: 'super_like',
    message: 'Love your travel photos!',
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
    name: 'Kavya',
    age: 26,
    photoUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400',
    isBlurred: false,
  },
];

// === Incognito Demo Data ===

export const DEMO_INCOGNITO_PROFILES: import('@/types').IncognitoProfile[] = [
  {
    id: 'inc_1', username: 'Midnight_Rose', age: 24, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400',
    desires: ['Deep late-night conversations', 'Someone who gets my humor'],
    desireCategories: ['romantic', 'intellectual'], distance: 3.2, city: 'Mumbai',
    bio: 'Night owl seeking meaningful connections under the stars.',
    isOnline: true, height: 165, bodyStructure: 'slim', hairColor: 'Black', eyeColor: 'Brown',
    relationshipIntent: 'Long-term', interests: ['Music', 'Poetry', 'Stargazing'], hobbies: ['Writing', 'Cooking', 'Reading'], faceUnblurred: false,
  },
  {
    id: 'inc_2', username: 'Wanderlust_Soul', age: 26, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    desires: ['Adventure partner', 'Spontaneous weekend trips'],
    desireCategories: ['adventurous', 'social'], distance: 5.1, city: 'Mumbai',
    bio: 'Life is too short for boring plans. Let\'s get lost together.',
    isOnline: true, height: 160, bodyStructure: 'athletic', hairColor: 'Brown', eyeColor: 'Hazel',
    relationshipIntent: 'Short-term', interests: ['Travel', 'Hiking', 'Photography'], hobbies: ['Backpacking', 'Surfing', 'Journaling'], faceUnblurred: false,
  },
  {
    id: 'inc_3', username: 'Velvet_Dreams', age: 23, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400',
    desires: ['Creative collaborator', 'Art gallery dates'],
    desireCategories: ['creative', 'romantic'], distance: 1.8, city: 'Mumbai',
    bio: 'Artist by passion, dreamer by nature.',
    isOnline: false, height: 158, bodyStructure: 'slim', hairColor: 'Black', eyeColor: 'Dark Brown',
    relationshipIntent: 'Long-term', interests: ['Art', 'Design', 'Film'], hobbies: ['Painting', 'Sculpting', 'Cinema'], faceUnblurred: false,
  },
  {
    id: 'inc_4', username: 'Phoenix_Fire', age: 27, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    desires: ['Intellectual debates', 'Book exchange partner'],
    desireCategories: ['intellectual', 'spiritual'], distance: 7.4, city: 'Pune',
    bio: 'Rising from the ashes of mundane conversations.',
    isOnline: true, height: 170, bodyStructure: 'athletic', hairColor: 'Auburn', eyeColor: 'Green',
    relationshipIntent: 'Long-term', interests: ['Philosophy', 'Science', 'Literature'], hobbies: ['Reading', 'Debating', 'Chess'], faceUnblurred: true,
  },
  {
    id: 'inc_5', username: 'Stargazer_22', age: 22, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=400',
    desires: ['Someone to stargaze with', 'Deep philosophical talks'],
    desireCategories: ['spiritual', 'romantic'], distance: 2.5, city: 'Mumbai',
    bio: 'Looking up at the sky, looking for you.',
    isOnline: false, height: 155, bodyStructure: 'curvy', hairColor: 'Black', eyeColor: 'Brown',
    relationshipIntent: 'Figuring out', interests: ['Astronomy', 'Philosophy', 'Music'], hobbies: ['Stargazing', 'Meditation', 'Guitar'], faceUnblurred: false,
  },
  {
    id: 'inc_6', username: 'Neon_Butterfly', age: 25, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400',
    desires: ['Dance floor chemistry', 'Festival buddy'],
    desireCategories: ['social', 'adventurous'], distance: 4.0, city: 'Mumbai',
    bio: 'Transforming every moment into magic.',
    isOnline: true, height: 163, bodyStructure: 'slim', hairColor: 'Highlighted', eyeColor: 'Brown',
    relationshipIntent: 'Short-term', interests: ['Dancing', 'Music Festivals', 'Fashion'], hobbies: ['Dancing', 'DJing', 'Styling'], faceUnblurred: false,
  },
  {
    id: 'inc_7', username: 'Mystic_Luna', age: 28, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400',
    desires: ['Yoga partner', 'Mindfulness companion'],
    desireCategories: ['spiritual', 'creative'], distance: 6.8, city: 'Bangalore',
    bio: 'Finding peace in chaos, seeking light in darkness.',
    isOnline: false, height: 167, bodyStructure: 'athletic', hairColor: 'Black', eyeColor: 'Dark Brown',
    relationshipIntent: 'Long-term', interests: ['Yoga', 'Meditation', 'Wellness'], hobbies: ['Yoga', 'Herbalism', 'Journaling'], faceUnblurred: true,
  },
  {
    id: 'inc_8', username: 'Cherry_Blossom', age: 23, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
    desires: ['Coffee date vibes', 'Rainy day cuddles'],
    desireCategories: ['romantic', 'social'], distance: 1.2, city: 'Mumbai',
    bio: 'Blooming where I\'m planted. Come grow with me.',
    isOnline: true, height: 157, bodyStructure: 'average', hairColor: 'Black', eyeColor: 'Brown',
    relationshipIntent: 'Long-term', interests: ['Coffee', 'Books', 'Gardening'], hobbies: ['Baking', 'Gardening', 'Crafting'], faceUnblurred: false,
  },
  {
    id: 'inc_9', username: 'Electric_Sage', age: 26, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    desires: ['Music jam sessions', 'Vinyl collection sharing'],
    desireCategories: ['creative', 'intellectual'], distance: 3.9, city: 'Mumbai',
    bio: 'Electricity runs through my veins, wisdom in my soul.',
    isOnline: true, height: 164, bodyStructure: 'slim', hairColor: 'Brown', eyeColor: 'Hazel',
    relationshipIntent: 'Short-term', interests: ['Music Production', 'Vinyl', 'Jazz'], hobbies: ['Producing', 'Piano', 'Record Hunting'], faceUnblurred: false,
  },
  {
    id: 'inc_10', username: 'Ocean_Whisper', age: 24, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1504439904031-93ded9f93e4e?w=400',
    desires: ['Beach sunset walks', 'Travel companion'],
    desireCategories: ['adventurous', 'romantic'], distance: 8.5, city: 'Goa',
    bio: 'The ocean whispers secrets only hearts can hear.',
    isOnline: false, height: 162, bodyStructure: 'curvy', hairColor: 'Wavy Brown', eyeColor: 'Brown',
    relationshipIntent: 'Figuring out', interests: ['Ocean', 'Travel', 'Sunsets'], hobbies: ['Swimming', 'Snorkeling', 'Shell Collecting'], faceUnblurred: false,
  },
  {
    id: 'inc_11', username: 'Shadow_Dancer', age: 25, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1506956191951-7a88da4435e5?w=400',
    desires: ['Late night dance sessions', 'Someone fearless'],
    desireCategories: ['adventurous', 'creative'], distance: 2.1, city: 'Mumbai',
    bio: 'Dancing between light and shadow.',
    isOnline: true, height: 168, bodyStructure: 'athletic', hairColor: 'Black', eyeColor: 'Dark Brown',
    relationshipIntent: 'Short-term', interests: ['Dance', 'Fitness', 'Nightlife'], hobbies: ['Contemporary Dance', 'Salsa', 'Boxing'], faceUnblurred: true,
  },
  {
    id: 'inc_12', username: 'Golden_Hour', age: 27, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=400',
    desires: ['Photography adventures', 'Golden hour shoots'],
    desireCategories: ['creative', 'social'], distance: 4.7, city: 'Delhi',
    bio: 'Everything is more beautiful in golden light.',
    isOnline: false, height: 161, bodyStructure: 'slim', hairColor: 'Blonde Highlights', eyeColor: 'Brown',
    relationshipIntent: 'Long-term', interests: ['Photography', 'Travel', 'Nature'], hobbies: ['Landscape Photography', 'Hiking', 'Editing'], faceUnblurred: false,
  },
  {
    id: 'inc_13', username: 'Rebel_Heart', age: 24, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1464863979621-258859e62245?w=400',
    desires: ['Rule-breaking adventures', 'No-filter conversations'],
    desireCategories: ['adventurous', 'social'], distance: 5.3, city: 'Mumbai',
    bio: 'Breaking rules and hearts since \'99.',
    isOnline: true, height: 166, bodyStructure: 'average', tattoos: true, piercings: true,
    hairColor: 'Red', eyeColor: 'Green',
    relationshipIntent: 'Open to anything', interests: ['Tattoo Art', 'Rock Music', 'Motorcycles'], hobbies: ['Riding', 'Sketching', 'Concerts'], faceUnblurred: false,
  },
  {
    id: 'inc_14', username: 'Silk_Road', age: 29, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1485893086445-ed75865251e0?w=400',
    desires: ['Cultural exploration', 'Fine dining partner'],
    desireCategories: ['intellectual', 'social'], distance: 9.2, city: 'Hyderabad',
    bio: 'Traveling through cultures, one conversation at a time.',
    isOnline: false, height: 172, bodyStructure: 'slim', hairColor: 'Black', eyeColor: 'Brown',
    relationshipIntent: 'Long-term', interests: ['Culture', 'Cuisine', 'History'], hobbies: ['Cooking', 'Wine Tasting', 'Museum Visits'], faceUnblurred: true,
  },
  {
    id: 'inc_15', username: 'Aurora_Sky', age: 22, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=400',
    desires: ['Northern lights trip', 'Astronomy buddy'],
    desireCategories: ['spiritual', 'adventurous'], distance: 3.6, city: 'Mumbai',
    bio: 'Chasing auroras and authentic connections.',
    isOnline: true, height: 156, bodyStructure: 'curvy', hairColor: 'Black', eyeColor: 'Brown',
    relationshipIntent: 'Figuring out', interests: ['Astronomy', 'Nature', 'Spirituality'], hobbies: ['Telescope Viewing', 'Camping', 'Crystal Collecting'], faceUnblurred: false,
  },
  {
    id: 'inc_16', username: 'Crimson_Tide', age: 26, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1529635204996-ef54f42e1804?w=400',
    desires: ['Competitive board game nights', 'Cooking experiments together'],
    desireCategories: ['social', 'creative'], distance: 2.7, city: 'Mumbai',
    bio: 'Fiercely competitive but fiercely loyal.',
    isOnline: true, height: 164, bodyStructure: 'athletic', hairColor: 'Black', eyeColor: 'Brown',
    relationshipIntent: 'Long-term', interests: ['Board Games', 'Cooking', 'Fitness'], hobbies: ['Strategy Games', 'Meal Prep', 'Running'], faceUnblurred: false,
  },
  {
    id: 'inc_17', username: 'Velvet_Storm', age: 23, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?w=400',
    desires: ['Midnight road trips', 'Raw honest conversations'],
    desireCategories: ['adventurous', 'intellectual'], distance: 4.1, city: 'Mumbai',
    bio: 'Soft outside, thunder inside. Handle with curiosity.',
    isOnline: false, height: 159, bodyStructure: 'slim', hairColor: 'Dark Brown', eyeColor: 'Dark Brown',
    relationshipIntent: 'Figuring out', interests: ['Road Trips', 'Psychology', 'Poetry'], hobbies: ['Driving', 'Journaling', 'Spoken Word'], faceUnblurred: false,
  },
  {
    id: 'inc_18', username: 'Ivory_Flame', age: 25, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=400',
    desires: ['Partner in crime for food crawls', 'Lazy Sunday mornings'],
    desireCategories: ['romantic', 'social'], distance: 1.5, city: 'Mumbai',
    bio: 'Feed me tacos and tell me I\'m pretty.',
    isOnline: true, height: 160, bodyStructure: 'curvy', hairColor: 'Brown', eyeColor: 'Hazel',
    relationshipIntent: 'Short-term', interests: ['Food', 'Comedy', 'Travel'], hobbies: ['Street Food Tours', 'Stand-up Comedy', 'Brunch Hopping'], faceUnblurred: true,
  },
  {
    id: 'inc_19', username: 'Moonlit_Fox', age: 27, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1491349174775-aaafddd81942?w=400',
    desires: ['Someone who reads between the lines', 'Quiet library dates'],
    desireCategories: ['intellectual', 'romantic'], distance: 6.3, city: 'Pune',
    bio: 'Cunning mind, gentle heart. Let\'s outsmart the world together.',
    isOnline: false, height: 167, bodyStructure: 'slim', hairColor: 'Black', eyeColor: 'Brown',
    relationshipIntent: 'Long-term', interests: ['Literature', 'Chess', 'Film Noir'], hobbies: ['Book Clubs', 'Crosswords', 'Classic Cinema'], faceUnblurred: false,
  },
  {
    id: 'inc_20', username: 'Prism_Light', age: 24, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?w=400',
    desires: ['Festival season companion', 'Spontaneous dancing in the rain'],
    desireCategories: ['adventurous', 'creative'], distance: 3.4, city: 'Mumbai',
    bio: 'I see the world in color. Come paint with me.',
    isOnline: true, height: 162, bodyStructure: 'average', hairColor: 'Highlighted', eyeColor: 'Brown',
    relationshipIntent: 'Open to anything', interests: ['Music Festivals', 'Art', 'Fashion'], hobbies: ['Painting', 'Thrifting', 'Dancing'], faceUnblurred: false,
  },
  {
    id: 'inc_21', username: 'Sage_Whisper', age: 28, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1546961342-ea1f71b193f3?w=400',
    desires: ['Mindful morning walks', 'Someone who values silence'],
    desireCategories: ['spiritual', 'romantic'], distance: 5.8, city: 'Bangalore',
    bio: 'In a world full of noise, I choose stillness.',
    isOnline: false, height: 170, bodyStructure: 'athletic', hairColor: 'Black', eyeColor: 'Dark Brown',
    relationshipIntent: 'Long-term', interests: ['Meditation', 'Wellness', 'Tea Ceremonies'], hobbies: ['Yoga', 'Herbalism', 'Nature Walks'], faceUnblurred: true,
  },
  {
    id: 'inc_22', username: 'Ember_Kiss', age: 22, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1504703395950-b89145a5425b?w=400',
    desires: ['Netflix marathon partner', 'Someone who steals my fries'],
    desireCategories: ['romantic', 'social'], distance: 1.9, city: 'Mumbai',
    bio: 'Warm like embers, sweet like a first kiss.',
    isOnline: true, height: 155, bodyStructure: 'slim', hairColor: 'Black', eyeColor: 'Brown',
    relationshipIntent: 'Short-term', interests: ['Movies', 'Anime', 'Gaming'], hobbies: ['Binge Watching', 'Cosplay', 'Digital Art'], faceUnblurred: false,
  },
  {
    id: 'inc_23', username: 'Wild_Orchid', age: 26, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400',
    desires: ['Scuba diving adventures', 'Campfire guitar sessions'],
    desireCategories: ['adventurous', 'creative'], distance: 7.1, city: 'Goa',
    bio: 'Wild at heart, rooted in kindness.',
    isOnline: true, height: 165, bodyStructure: 'athletic', hairColor: 'Wavy Brown', eyeColor: 'Green',
    relationshipIntent: 'Figuring out', interests: ['Scuba Diving', 'Music', 'Nature'], hobbies: ['Guitar', 'Camping', 'Surfing'], faceUnblurred: false,
  },
  {
    id: 'inc_24', username: 'Neon_Mirage', age: 24, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400',
    desires: ['Late-night karaoke sessions', 'Exploring hidden city spots'],
    desireCategories: ['social', 'adventurous'], distance: 2.3, city: 'Mumbai',
    bio: 'Now you see me, now you\'re intrigued.',
    isOnline: false, height: 163, bodyStructure: 'average', hairColor: 'Black', eyeColor: 'Brown',
    relationshipIntent: 'Open to anything', interests: ['Karaoke', 'Urban Exploring', 'Nightlife'], hobbies: ['Singing', 'Photography', 'Street Art Tours'], faceUnblurred: false,
  },
  {
    id: 'inc_25', username: 'Copper_Moon', age: 29, gender: 'female',
    photoUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400',
    desires: ['Wine and cheese evenings', 'Deep debates about everything'],
    desireCategories: ['intellectual', 'social'], distance: 4.6, city: 'Delhi',
    bio: 'Aged like fine wine. Still aging, actually.',
    isOnline: true, height: 171, bodyStructure: 'slim', hairColor: 'Auburn', eyeColor: 'Hazel',
    relationshipIntent: 'Long-term', interests: ['Wine', 'Philosophy', 'Economics'], hobbies: ['Wine Tasting', 'Debating', 'Writing'], faceUnblurred: true,
  },
];

export const DEMO_TOD_POSTS: import('@/types').TruthOrDarePost[] = [
  { id: 'tod_1', authorId: 'inc_1', authorName: 'Midnight_Rose', authorAge: 24, authorPhotoUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400', type: 'truth', content: 'What is the one thing you\'ve never told anyone about yourself?', responseCount: 23, createdAt: Date.now() - 1000 * 60 * 30, isAnonymous: false },
  { id: 'tod_2', authorId: 'inc_6', authorName: 'Neon_Butterfly', authorAge: 25, authorPhotoUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400', type: 'dare', content: 'Send a voice note singing your favorite song to the last person you matched with!', responseCount: 15, createdAt: Date.now() - 1000 * 60 * 60 * 2, isAnonymous: false },
  { id: 'tod_3', authorId: 'inc_4', authorName: 'Phoenix_Fire', authorAge: 27, authorPhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', type: 'truth', content: 'What\'s the biggest red flag you\'ve ignored in a relationship?', responseCount: 45, createdAt: Date.now() - 1000 * 60 * 60 * 4, isAnonymous: false },
  { id: 'tod_4', authorId: 'inc_8', authorName: 'Cherry_Blossom', authorAge: 23, authorPhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', type: 'dare', content: 'Post a photo of yourself doing your best dance move right now!', responseCount: 8, createdAt: Date.now() - 1000 * 60 * 60 * 6, isAnonymous: false },
  { id: 'tod_5', authorId: 'inc_3', authorName: 'Velvet_Dreams', authorAge: 23, authorPhotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400', type: 'truth', content: 'If you could live inside any painting, which one would you choose and why?', responseCount: 19, createdAt: Date.now() - 1000 * 60 * 60 * 8, isAnonymous: false },
  { id: 'tod_6', authorId: 'inc_13', authorName: 'Rebel_Heart', authorAge: 24, authorPhotoUrl: 'https://images.unsplash.com/photo-1464863979621-258859e62245?w=400', type: 'dare', content: 'Send a flirty message to someone you\'ve been too shy to talk to!', responseCount: 31, createdAt: Date.now() - 1000 * 60 * 60 * 10, isAnonymous: false },
  { id: 'tod_7', authorId: 'inc_9', authorName: 'Electric_Sage', authorAge: 26, authorPhotoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', type: 'truth', content: 'What song describes your love life right now?', responseCount: 27, createdAt: Date.now() - 1000 * 60 * 60 * 12, isAnonymous: false },
  { id: 'tod_8', authorId: 'inc_11', authorName: 'Shadow_Dancer', authorAge: 25, authorPhotoUrl: 'https://images.unsplash.com/photo-1506956191951-7a88da4435e5?w=400', type: 'dare', content: 'Record yourself doing 10 jumping jacks and share it in the chat!', responseCount: 12, createdAt: Date.now() - 1000 * 60 * 60 * 14, isAnonymous: false },
  { id: 'tod_9', authorId: 'inc_5', authorName: 'Stargazer_22', authorAge: 22, authorPhotoUrl: 'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=400', type: 'truth', content: 'What\'s your most embarrassing first date story?', responseCount: 38, createdAt: Date.now() - 1000 * 60 * 60 * 16, isAnonymous: false },
  { id: 'tod_10', authorId: 'inc_15', authorName: 'Aurora_Sky', authorAge: 22, authorPhotoUrl: 'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=400', type: 'dare', content: 'Write a 4-line poem about the last person you had a crush on!', responseCount: 21, createdAt: Date.now() - 1000 * 60 * 60 * 18, isAnonymous: false },
];

export const DEMO_TOD_RESPONSES: import('@/types').TodResponse[] = [
  // tod_1 — 3 responses
  { id: 'tr_1', postId: 'tod_1', responderId: 'inc_6', responderName: 'Neon_Butterfly', responderPhotoUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400', responseType: 'text', content: 'I once cried watching a sunset because it reminded me of my childhood.', status: 'pending', createdAt: Date.now() - 1000 * 60 * 20 },
  { id: 'tr_2', postId: 'tod_1', responderId: 'inc_8', responderName: 'Cherry_Blossom', responderPhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', responseType: 'picture', content: 'Here is my secret talent!', mediaUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=400', status: 'correct', createdAt: Date.now() - 1000 * 60 * 40 },
  { id: 'tr_2b', postId: 'tod_1', responderId: 'inc_9', responderName: 'Electric_Sage', responderPhotoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', responseType: 'text', content: 'I still sleep with a stuffed animal. There, I said it.', status: 'pending', createdAt: Date.now() - 1000 * 60 * 55 },
  // tod_2 — 3 responses
  { id: 'tr_3', postId: 'tod_2', responderId: 'inc_3', responderName: 'Velvet_Dreams', responderPhotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400', responseType: 'audio', content: 'Sang my heart out for this dare!', status: 'pending', createdAt: Date.now() - 1000 * 60 * 60 },
  { id: 'tr_3b', postId: 'tod_2', responderId: 'inc_4', responderName: 'Phoenix_Fire', responderPhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', responseType: 'text', content: 'Sent a voice note of me humming — does that count?', status: 'pending', createdAt: Date.now() - 1000 * 60 * 75 },
  { id: 'tr_3c', postId: 'tod_2', responderId: 'inc_15', responderName: 'Aurora_Sky', responderPhotoUrl: 'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=400', responseType: 'video', content: 'Full karaoke performance incoming!', mediaUrl: 'https://example.com/video2.mp4', status: 'correct', createdAt: Date.now() - 1000 * 60 * 80 },
  // tod_3 — 3 responses
  { id: 'tr_4', postId: 'tod_3', responderId: 'inc_11', responderName: 'Shadow_Dancer', responderPhotoUrl: 'https://images.unsplash.com/photo-1506956191951-7a88da4435e5?w=400', responseType: 'video', content: 'This is my honest answer on camera.', mediaUrl: 'https://example.com/video.mp4', status: 'declined', createdAt: Date.now() - 1000 * 60 * 90 },
  { id: 'tr_4b', postId: 'tod_3', responderId: 'inc_5', responderName: 'Stargazer_22', responderPhotoUrl: 'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=400', responseType: 'text', content: 'Ignored that they never asked me a single question about myself. Ugh.', status: 'pending', createdAt: Date.now() - 1000 * 60 * 100 },
  { id: 'tr_4c', postId: 'tod_3', responderId: 'inc_13', responderName: 'Rebel_Heart', responderPhotoUrl: 'https://images.unsplash.com/photo-1464863979621-258859e62245?w=400', responseType: 'text', content: 'They said they didn\'t believe in labels… turns out they were married.', status: 'pending', createdAt: Date.now() - 1000 * 60 * 110 },
  // tod_4 — 2 responses
  { id: 'tr_5', postId: 'tod_4', responderId: 'inc_5', responderName: 'Stargazer_22', responderPhotoUrl: 'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=400', responseType: 'text', content: 'My best dance move is the robot. Don\'t judge!', status: 'pending', createdAt: Date.now() - 1000 * 60 * 120 },
  { id: 'tr_5b', postId: 'tod_4', responderId: 'inc_3', responderName: 'Velvet_Dreams', responderPhotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400', responseType: 'picture', content: 'Caught mid-spin!', mediaUrl: 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=400', status: 'pending', createdAt: Date.now() - 1000 * 60 * 130 },
  // tod_5 — 2 responses
  { id: 'tr_6', postId: 'tod_5', responderId: 'inc_6', responderName: 'Neon_Butterfly', responderPhotoUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400', responseType: 'text', content: 'Starry Night by Van Gogh — I want to float through that sky forever.', status: 'pending', createdAt: Date.now() - 1000 * 60 * 140 },
  { id: 'tr_6b', postId: 'tod_5', responderId: 'inc_11', responderName: 'Shadow_Dancer', responderPhotoUrl: 'https://images.unsplash.com/photo-1506956191951-7a88da4435e5?w=400', responseType: 'text', content: 'A Sunday on La Grande Jatte — just chilling by the river all day.', status: 'correct', createdAt: Date.now() - 1000 * 60 * 150 },
  // tod_6 — 2 responses
  { id: 'tr_7', postId: 'tod_6', responderId: 'inc_8', responderName: 'Cherry_Blossom', responderPhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', responseType: 'text', content: 'Just did it. Hands are still shaking. Wish me luck!', status: 'pending', createdAt: Date.now() - 1000 * 60 * 160 },
  { id: 'tr_7b', postId: 'tod_6', responderId: 'inc_9', responderName: 'Electric_Sage', responderPhotoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', responseType: 'audio', content: 'Recorded a voice message — way easier than typing!', status: 'pending', createdAt: Date.now() - 1000 * 60 * 170 },
  // tod_7 — 2 responses
  { id: 'tr_8', postId: 'tod_7', responderId: 'inc_4', responderName: 'Phoenix_Fire', responderPhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', responseType: 'text', content: '"Complicated" by Avril Lavigne. Classic and accurate.', status: 'pending', createdAt: Date.now() - 1000 * 60 * 180 },
  { id: 'tr_8b', postId: 'tod_7', responderId: 'inc_15', responderName: 'Aurora_Sky', responderPhotoUrl: 'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=400', responseType: 'text', content: '"Espresso" by Sabrina Carpenter — it\'s giving obsession.', status: 'correct', createdAt: Date.now() - 1000 * 60 * 190 },
  // tod_8 — 1 response
  { id: 'tr_9', postId: 'tod_8', responderId: 'inc_6', responderName: 'Neon_Butterfly', responderPhotoUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400', responseType: 'video', content: 'Done! Almost knocked over a lamp though.', mediaUrl: 'https://example.com/video3.mp4', status: 'pending', createdAt: Date.now() - 1000 * 60 * 200 },
  // tod_9 — 3 responses
  { id: 'tr_10', postId: 'tod_9', responderId: 'inc_13', responderName: 'Rebel_Heart', responderPhotoUrl: 'https://images.unsplash.com/photo-1464863979621-258859e62245?w=400', responseType: 'text', content: 'I accidentally called them by my ex\'s name. At dinner. With their parents.', status: 'pending', createdAt: Date.now() - 1000 * 60 * 210 },
  { id: 'tr_10b', postId: 'tod_9', responderId: 'inc_8', responderName: 'Cherry_Blossom', responderPhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', responseType: 'text', content: 'Tripped walking into the restaurant and face-planted into the hostess stand.', status: 'pending', createdAt: Date.now() - 1000 * 60 * 220 },
  { id: 'tr_10c', postId: 'tod_9', responderId: 'inc_3', responderName: 'Velvet_Dreams', responderPhotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400', responseType: 'text', content: 'I showed up to the wrong restaurant. Sat there for 45 minutes.', status: 'correct', createdAt: Date.now() - 1000 * 60 * 230 },
  // tod_10 — 2 responses
  { id: 'tr_11', postId: 'tod_10', responderId: 'inc_5', responderName: 'Stargazer_22', responderPhotoUrl: 'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=400', responseType: 'text', content: 'Your eyes like stars, your laugh like rain / I think of you and go insane / A fleeting glance, a gentle sigh / For you I\'d learn to paint the sky.', status: 'pending', createdAt: Date.now() - 1000 * 60 * 240 },
  { id: 'tr_11b', postId: 'tod_10', responderId: 'inc_4', responderName: 'Phoenix_Fire', responderPhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', responseType: 'text', content: 'Roses are red / Violets are blue / I swiped right / And so did you.', status: 'pending', createdAt: Date.now() - 1000 * 60 * 250 },
];

export const DEMO_INCOGNITO_CONVERSATIONS: import('@/types').IncognitoConversation[] = [
  { id: 'ic_1', participantId: 'inc_1', participantName: 'Midnight_Rose', participantAge: 24, participantPhotoUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400', lastMessage: 'That was such a fun truth! Your turn now...', lastMessageAt: Date.now() - 1000 * 60 * 5, unreadCount: 2, connectionSource: 'tod' },
  { id: 'ic_2', participantId: 'inc_6', participantName: 'Neon_Butterfly', participantAge: 25, participantPhotoUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400', lastMessage: 'See you at the festival this weekend?', lastMessageAt: Date.now() - 1000 * 60 * 30, unreadCount: 0, connectionSource: 'room' },
  { id: 'ic_3', participantId: 'inc_8', participantName: 'Cherry_Blossom', participantAge: 23, participantPhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', lastMessage: 'I love that coffee place too!', lastMessageAt: Date.now() - 1000 * 60 * 60 * 2, unreadCount: 1, connectionSource: 'desire' },
  { id: 'ic_4', participantId: 'inc_11', participantName: 'Shadow_Dancer', participantAge: 25, participantPhotoUrl: 'https://images.unsplash.com/photo-1506956191951-7a88da4435e5?w=400', lastMessage: 'The dance class was amazing!', lastMessageAt: Date.now() - 1000 * 60 * 60 * 5, unreadCount: 0, connectionSource: 'friend' },
  { id: 'ic_5', participantId: 'inc_4', participantName: 'Phoenix_Fire', participantAge: 27, participantPhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', lastMessage: 'Have you read that book I recommended?', lastMessageAt: Date.now() - 1000 * 60 * 60 * 12, unreadCount: 3, connectionSource: 'tod' },
];

export const DEMO_INCOGNITO_MESSAGES: import('@/types').IncognitoMessage[] = [
  { id: 'im_1', conversationId: 'ic_1', senderId: 'inc_1', content: 'Hey! I saw your answer on Truth or Dare. So brave!', createdAt: Date.now() - 1000 * 60 * 60, isRead: true },
  { id: 'im_2', conversationId: 'ic_1', senderId: 'me', content: 'Haha thanks! It was nerve-wracking to share that.', createdAt: Date.now() - 1000 * 60 * 55, isRead: true },
  { id: 'im_3', conversationId: 'ic_1', senderId: 'inc_1', content: 'I totally get it. Your turn - truth or dare?', createdAt: Date.now() - 1000 * 60 * 50, isRead: true },
  { id: 'im_4', conversationId: 'ic_1', senderId: 'me', content: 'Truth! I\'m feeling bold today.', createdAt: Date.now() - 1000 * 60 * 45, isRead: true },
  { id: 'im_5', conversationId: 'ic_1', senderId: 'inc_1', content: 'Okay... What\'s your biggest guilty pleasure?', createdAt: Date.now() - 1000 * 60 * 40, isRead: true },
  { id: 'im_6', conversationId: 'ic_1', senderId: 'me', content: 'I watch K-dramas until 3 AM and cry. Don\'t judge me!', createdAt: Date.now() - 1000 * 60 * 35, isRead: true },
  { id: 'im_7', conversationId: 'ic_1', senderId: 'inc_1', content: 'OMG same! Which one are you watching now?', createdAt: Date.now() - 1000 * 60 * 30, isRead: true },
  { id: 'im_8', conversationId: 'ic_1', senderId: 'me', content: 'Crash Landing on You for the third time...', createdAt: Date.now() - 1000 * 60 * 25, isRead: true },
  { id: 'im_9', conversationId: 'ic_1', senderId: 'inc_1', content: 'That was such a fun truth! Your turn now...', createdAt: Date.now() - 1000 * 60 * 5, isRead: false },
  { id: 'im_10', conversationId: 'ic_2', senderId: 'inc_6', content: 'Hey! Are you going to the music fest?', createdAt: Date.now() - 1000 * 60 * 60 * 2, isRead: true },
  { id: 'im_11', conversationId: 'ic_2', senderId: 'me', content: 'Yes! I got VIP passes!', createdAt: Date.now() - 1000 * 60 * 60, isRead: true },
  { id: 'im_12', conversationId: 'ic_2', senderId: 'inc_6', content: 'See you at the festival this weekend?', createdAt: Date.now() - 1000 * 60 * 30, isRead: true },
  { id: 'im_13', conversationId: 'ic_3', senderId: 'inc_8', content: 'Your desire for coffee dates caught my eye!', createdAt: Date.now() - 1000 * 60 * 60 * 3, isRead: true },
  { id: 'im_14', conversationId: 'ic_3', senderId: 'me', content: 'Great taste! Do you know Blue Tokai?', createdAt: Date.now() - 1000 * 60 * 60 * 2.5, isRead: true },
  { id: 'im_15', conversationId: 'ic_3', senderId: 'inc_8', content: 'I love that coffee place too!', createdAt: Date.now() - 1000 * 60 * 60 * 2, isRead: false },
  { id: 'im_16', conversationId: 'ic_4', senderId: 'inc_11', content: 'We should totally go dancing sometime!', createdAt: Date.now() - 1000 * 60 * 60 * 6, isRead: true },
  { id: 'im_17', conversationId: 'ic_4', senderId: 'me', content: 'I know a great salsa class on Saturdays!', createdAt: Date.now() - 1000 * 60 * 60 * 5.5, isRead: true },
  { id: 'im_18', conversationId: 'ic_4', senderId: 'inc_11', content: 'The dance class was amazing!', createdAt: Date.now() - 1000 * 60 * 60 * 5, isRead: true },
  { id: 'im_19', conversationId: 'ic_5', senderId: 'inc_4', content: 'I just finished "Sapiens". Have you read it?', createdAt: Date.now() - 1000 * 60 * 60 * 13, isRead: true },
  { id: 'im_20', conversationId: 'ic_5', senderId: 'inc_4', content: 'Have you read that book I recommended?', createdAt: Date.now() - 1000 * 60 * 60 * 12, isRead: false },
];

export const DEMO_ROOM_MESSAGES = [
  { id: 'rm_1', senderId: 'inc_1', senderName: 'Midnight_Rose', content: 'Hey everyone! New here.', createdAt: Date.now() - 1000 * 60 * 10 },
  { id: 'rm_2', senderId: 'inc_6', senderName: 'Neon_Butterfly', content: 'Welcome! This room is awesome.', createdAt: Date.now() - 1000 * 60 * 8 },
  { id: 'rm_3', senderId: 'inc_8', senderName: 'Cherry_Blossom', content: 'Anyone up for a game?', createdAt: Date.now() - 1000 * 60 * 6 },
  { id: 'rm_4', senderId: 'inc_11', senderName: 'Shadow_Dancer', content: 'Count me in!', createdAt: Date.now() - 1000 * 60 * 4 },
  { id: 'rm_5', senderId: 'me', senderName: 'You', content: 'Sounds fun! What game?', createdAt: Date.now() - 1000 * 60 * 2 },
  { id: 'rm_6', senderId: 'inc_3', senderName: 'Velvet_Dreams', content: 'Let\'s play 20 questions!', createdAt: Date.now() - 1000 * 60 },
];

// Demo Trending T&D Prompts
export const DEMO_TRENDING_PROMPTS: import('@/types').TodPrompt[] = [
  {
    id: 'tp_truth_1',
    type: 'truth',
    text: "What's the most spontaneous thing you've ever done for someone you liked?",
    isTrending: true,
    ownerUserId: 'inc_2',
    ownerName: 'Wanderlust_Soul',
    ownerPhotoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    ownerAge: 26,
    ownerGender: 'female',
    answerCount: 42,
    activeCount: 18,
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
    expiresAt: Date.now() - 1000 * 60 * 60 * 2 + 7 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'tp_dare_1',
    type: 'dare',
    text: 'Record a 15-second video of your best impression of your celebrity crush!',
    isTrending: true,
    ownerUserId: 'inc_7',
    ownerName: 'Mystic_Luna',
    ownerPhotoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400',
    ownerAge: 28,
    ownerGender: 'female',
    answerCount: 27,
    activeCount: 11,
    createdAt: Date.now() - 1000 * 60 * 60 * 3,
    expiresAt: Date.now() - 1000 * 60 * 60 * 3 + 7 * 24 * 60 * 60 * 1000,
  },
];

export const DEMO_OTHER_PROMPTS: import('@/types').TodPrompt[] = [
  {
    id: 'tp_truth_2',
    type: 'truth',
    text: "What's a red flag you ignored because the person was too attractive?",
    isTrending: false,
    ownerUserId: 'inc_3',
    ownerName: 'Velvet_Dreams',
    ownerPhotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400',
    ownerAge: 23,
    ownerGender: 'female',
    answerCount: 19,
    activeCount: 7,
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
    expiresAt: Date.now() - 1000 * 60 * 60 * 5 + 7 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'tp_dare_2',
    type: 'dare',
    text: 'Send a voice note confessing your most embarrassing crush story!',
    isTrending: false,
    ownerUserId: 'inc_6',
    ownerName: 'Neon_Butterfly',
    ownerPhotoUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400',
    ownerAge: 25,
    ownerGender: 'female',
    answerCount: 14,
    activeCount: 5,
    createdAt: Date.now() - 1000 * 60 * 60 * 6,
    expiresAt: Date.now() - 1000 * 60 * 60 * 6 + 7 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'tp_truth_3',
    type: 'truth',
    text: "Have you ever pretended to like something just to impress a date?",
    isTrending: false,
    ownerUserId: 'inc_9',
    ownerName: 'Electric_Sage',
    ownerPhotoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    ownerAge: 26,
    ownerGender: 'female',
    answerCount: 31,
    activeCount: 12,
    createdAt: Date.now() - 1000 * 60 * 60 * 8,
    expiresAt: Date.now() - 1000 * 60 * 60 * 8 + 7 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'tp_dare_3',
    type: 'dare',
    text: 'Post a photo doing the cheesiest pickup line pose you can think of!',
    isTrending: false,
    ownerUserId: 'inc_4',
    ownerName: 'Phoenix_Fire',
    ownerPhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    ownerAge: 27,
    ownerGender: 'female',
    answerCount: 9,
    activeCount: 3,
    createdAt: Date.now() - 1000 * 60 * 60 * 10,
    expiresAt: Date.now() - 1000 * 60 * 60 * 10 + 7 * 24 * 60 * 60 * 1000,
  },
];

export const DEMO_OTHER_ANSWERS: import('@/types').TodAnswer[] = [
  // truth_2 answers
  { id: 'oa_1', promptId: 'tp_truth_2', userId: 'inc_1', userName: 'Midnight_Rose', userPhotoUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400', type: 'text', text: 'They were 45 minutes late every single time. But those eyes... I let it slide for 3 months.', likeCount: 11, createdAt: Date.now() - 1000 * 60 * 60 * 4 },
  { id: 'oa_2', promptId: 'tp_truth_2', userId: 'inc_8', userName: 'Cherry_Blossom', userPhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', type: 'text', text: 'He literally said he doesn\'t believe in texting back. I stayed for 2 more months.', likeCount: 16, createdAt: Date.now() - 1000 * 60 * 60 * 4.5 },
  { id: 'oa_3', promptId: 'tp_truth_2', userId: 'inc_5', userName: 'Stargazer_22', userPhotoUrl: 'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=400', type: 'voice', text: 'Voice answer', durationSec: 18, likeCount: 5, createdAt: Date.now() - 1000 * 60 * 60 * 5 },
  { id: 'oa_4', promptId: 'tp_truth_2', userId: 'inc_11', userName: 'Shadow_Dancer', userPhotoUrl: 'https://images.unsplash.com/photo-1506956191951-7a88da4435e5?w=400', type: 'text', text: 'She ghosted me twice and I STILL went on a third date. No regrets though, great sushi.', likeCount: 9, createdAt: Date.now() - 1000 * 60 * 60 * 5.5 },
  // dare_2 answers
  { id: 'oa_5', promptId: 'tp_dare_2', userId: 'inc_4', userName: 'Phoenix_Fire', userPhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', type: 'voice', text: 'Voice answer', durationSec: 32, likeCount: 14, createdAt: Date.now() - 1000 * 60 * 60 * 5.5 },
  { id: 'oa_6', promptId: 'tp_dare_2', userId: 'inc_13', userName: 'Rebel_Heart', userPhotoUrl: 'https://images.unsplash.com/photo-1464863979621-258859e62245?w=400', type: 'text', text: 'I had the BIGGEST crush on my teacher in 10th grade. I used to purposely fail tests so I could get "extra help" sessions.', likeCount: 20, createdAt: Date.now() - 1000 * 60 * 60 * 6 },
  { id: 'oa_7', promptId: 'tp_dare_2', userId: 'inc_3', userName: 'Velvet_Dreams', userPhotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400', type: 'voice', text: 'Voice answer', durationSec: 27, likeCount: 10, createdAt: Date.now() - 1000 * 60 * 60 * 6.5 },
  // truth_3 answers
  { id: 'oa_8', promptId: 'tp_truth_3', userId: 'inc_6', userName: 'Neon_Butterfly', userPhotoUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400', type: 'text', text: 'I pretended to love hiking. I hate hiking. Three months of blisters before I confessed.', likeCount: 24, createdAt: Date.now() - 1000 * 60 * 60 * 7 },
  { id: 'oa_9', promptId: 'tp_truth_3', userId: 'inc_9', userName: 'Electric_Sage', userPhotoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', type: 'text', text: 'Told her I was into poetry. She made me read Rumi at a coffee shop open mic. Never again.', likeCount: 17, createdAt: Date.now() - 1000 * 60 * 60 * 7.5 },
  { id: 'oa_10', promptId: 'tp_truth_3', userId: 'inc_1', userName: 'Midnight_Rose', userPhotoUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400', type: 'photo', text: 'Me pretending to enjoy rock climbing', mediaUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=400', likeCount: 13, createdAt: Date.now() - 1000 * 60 * 60 * 8 },
  { id: 'oa_11', promptId: 'tp_truth_3', userId: 'inc_4', userName: 'Phoenix_Fire', userPhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', type: 'text', text: 'I said I loved spicy food. First date at a Thai place. Tears streaming down my face. She thought I was emotional.', likeCount: 29, createdAt: Date.now() - 1000 * 60 * 60 * 8.5 },
  // dare_3 answers
  { id: 'oa_12', promptId: 'tp_dare_3', userId: 'inc_8', userName: 'Cherry_Blossom', userPhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', type: 'photo', text: 'Blue Steel meets "Are you a parking ticket?"', mediaUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400', likeCount: 15, createdAt: Date.now() - 1000 * 60 * 60 * 9 },
  { id: 'oa_13', promptId: 'tp_dare_3', userId: 'inc_5', userName: 'Stargazer_22', userPhotoUrl: 'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=400', type: 'text', text: 'Did the classic lean-on-wall pose with sunglasses indoors. My roommate is still laughing.', likeCount: 8, createdAt: Date.now() - 1000 * 60 * 60 * 9.5 },
];

// Demo Answers for Trending Prompts
export const DEMO_TRENDING_ANSWERS: import('@/types').TodAnswer[] = [
  // Truth prompt answers
  { id: 'ta_1', promptId: 'tp_truth_1', userId: 'inc_1', userName: 'Midnight_Rose', userPhotoUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400', type: 'text', text: 'I once drove 4 hours at midnight just to surprise my crush with their favorite flowers. They opened the door half-asleep and it was magical.', likeCount: 14, createdAt: Date.now() - 1000 * 60 * 30 },
  { id: 'ta_2', promptId: 'tp_truth_1', userId: 'inc_6', userName: 'Neon_Butterfly', userPhotoUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400', type: 'text', text: 'Booked a surprise trip to Goa. Didn\'t even tell them until we were at the airport. Best weekend ever.', likeCount: 9, createdAt: Date.now() - 1000 * 60 * 45 },
  { id: 'ta_3', promptId: 'tp_truth_1', userId: 'inc_8', userName: 'Cherry_Blossom', userPhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', type: 'photo', text: 'Made them a hand-painted portrait!', mediaUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400', likeCount: 22, createdAt: Date.now() - 1000 * 60 * 60 },
  { id: 'ta_4', promptId: 'tp_truth_1', userId: 'inc_11', userName: 'Shadow_Dancer', userPhotoUrl: 'https://images.unsplash.com/photo-1506956191951-7a88da4435e5?w=400', type: 'voice', text: 'Voice answer', durationSec: 23, likeCount: 7, createdAt: Date.now() - 1000 * 60 * 75 },
  { id: 'ta_5', promptId: 'tp_truth_1', userId: 'inc_4', userName: 'Phoenix_Fire', userPhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', type: 'text', text: 'Learned their favorite song on guitar in secret. Played it on our third date. They cried happy tears.', likeCount: 18, createdAt: Date.now() - 1000 * 60 * 90 },
  // Dare prompt answers
  { id: 'ta_6', promptId: 'tp_dare_1', userId: 'inc_3', userName: 'Velvet_Dreams', userPhotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400', type: 'video', text: 'My SRK impression!', mediaUrl: 'https://example.com/video_dare_1.mp4', durationSec: 14, likeCount: 31, createdAt: Date.now() - 1000 * 60 * 40 },
  { id: 'ta_7', promptId: 'tp_dare_1', userId: 'inc_9', userName: 'Electric_Sage', userPhotoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', type: 'text', text: 'Too shy for video but here goes: I did the RRR dance in my living room and my roommate caught me.', likeCount: 12, createdAt: Date.now() - 1000 * 60 * 55 },
  { id: 'ta_8', promptId: 'tp_dare_1', userId: 'inc_13', userName: 'Rebel_Heart', userPhotoUrl: 'https://images.unsplash.com/photo-1464863979621-258859e62245?w=400', type: 'photo', text: 'Striking my best Ranveer Singh pose!', mediaUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', likeCount: 19, createdAt: Date.now() - 1000 * 60 * 70 },
  { id: 'ta_9', promptId: 'tp_dare_1', userId: 'inc_5', userName: 'Stargazer_22', userPhotoUrl: 'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=400', type: 'voice', text: 'Voice answer', durationSec: 15, likeCount: 8, createdAt: Date.now() - 1000 * 60 * 85 },
  // Demo voice answers for testing playback
  { id: 'ta_demo_voice_1', promptId: 'tp_truth_1', userId: 'inc_10', userName: 'Ocean_Whisper', userPhotoUrl: 'https://images.unsplash.com/photo-1504439904031-93ded9f93e4e?w=400', type: 'voice', text: 'Voice answer', durationSec: 8, likeCount: 5, createdAt: Date.now() - 1000 * 60 * 50, visibility: 'public', isDemo: true },
  { id: 'ta_demo_voice_2', promptId: 'tp_dare_1', userId: 'inc_11', userName: 'Shadow_Dancer', userPhotoUrl: 'https://images.unsplash.com/photo-1506956191951-7a88da4435e5?w=400', type: 'voice', text: 'Voice answer', durationSec: 6, likeCount: 11, createdAt: Date.now() - 1000 * 60 * 60, visibility: 'public', isDemo: true },
  { id: 'ta_demo_voice_3', promptId: 'tp_truth_2', userId: 'inc_10', userName: 'Ocean_Whisper', userPhotoUrl: 'https://images.unsplash.com/photo-1504439904031-93ded9f93e4e?w=400', type: 'voice', text: 'Voice answer', durationSec: 10, likeCount: 7, createdAt: Date.now() - 1000 * 60 * 60 * 4.2, visibility: 'public', isDemo: true },
  // Anonymous demo answers
  { id: 'ta_anon_1', promptId: 'tp_truth_1', userId: 'inc_12', userName: 'Golden_Hour', userPhotoUrl: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=400', type: 'text', text: 'I secretly wrote love letters and left them on their desk for weeks. They never figured out it was me.', likeCount: 25, createdAt: Date.now() - 1000 * 60 * 20, isAnonymous: true, userGender: 'female', profileVisibility: 'blurred' as const },
  { id: 'ta_anon_2', promptId: 'tp_truth_2', userId: 'inc_14', userName: 'Silk_Road', userPhotoUrl: 'https://images.unsplash.com/photo-1485893086445-ed75865251e0?w=400', type: 'text', text: 'He would always cancel plans last minute. I pretended it didn\'t bother me for 6 months.', likeCount: 19, createdAt: Date.now() - 1000 * 60 * 60 * 3, isAnonymous: true, userGender: 'female', profileVisibility: 'blurred' as const },
];

export const isDemoMode = () => {
  return process.env.EXPO_PUBLIC_DEMO_MODE === 'true' ||
    process.env.EXPO_PUBLIC_CONVEX_URL?.includes('placeholder');
};
